### PR TITLE
Added a small optimization: instead of starting from the last master …

### PR DESCRIPTION
**Pull request by sharkgua**
…tree, start from the first one.

### CODE REVIEW

**Comment by Carlos-Augusto** [comment]
Is there a way to easily select between both algorithms?

**Comment by sharkgua** [comment]
One way would be to change maybeFirstMasterAndTime to maybeLastMasterAndTime
I can introduce a "safety switch" if you want: result unsuccessful -> trying the other algorithm

**Comment by Carlos-Augusto** [comment]
I like the idea of the switch, when you mentioned a safety switch based on the result, does that mean that one algorithm could fail and the other succeed?

Shouldn't they be equivalent?

**Comment by sharkgua** [comment]
> Shouldn't they be equivalent, just one faster than the other?

From all the hashes that I saw and tested that are made, they are. I always see the first found master tree being used again on the way back from the upper anchor to the lower one

**Comment by Carlos-Augusto** [comment]
I get it. I would say we should have an easy way to turn it off/on, maybe through a config variable, so that it is not dangerous just in case we have to promote stuff to production. Can you add a config value?

**Comment by sharkgua** [comment]
For sure!

**Comment by sharkgua** [comment]
Made the changes

**Comment by sharkgua** [comment]
Of course if I don't push it won't appear..

**Comment by Carlos-Augusto** [comment]
Looks great, let's merge

**Pull request merged**
